user:
  length:
    name_max_length: 50
    email_max_length: 100
    password_min_length: 6

product:
  length:
    name_min_length: 10
    price_min: 1
    quantity_min: 1
feedback:
  length:
    subject_max_length: 100
product_order:
  length:
    quantity_min: 1
